version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    # If you want to pass extra environment variables or volumes, do it here
    # environment:
    #   ADDITIONAL_ENV: "Something"
    # volumes:
    #   - .:/app  # only for local dev if you want live code mounting

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    # command: ["npm", "run", "start"]  # depends on your setup
